theme: minima
# Site settings
title: Andreas.
email: andreas@neumeier.org
description: >- # this means to ignore newlines until "baseurl:"
  Home of Andreas Neumeier.
# baseurl: "/twitter-new" # the subpath of your site, e.g. /blog
markdown: kramdown
url: "https://www.neumeier.org" # the base hostname & protocol for your site, e.g. http://example.com
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: andreasofthings
    github:  andreasofthings
    stackoverflow: "1569491"
    facebook: andreasofthings
    flickr: andreasofthings
    instagram: andreasofthings
    linkedin: andreasofthings
    keybase: andreasofthings
