theme: jekyll-theme-tactile
# Site settings
title: This is my name.
email: andreas@neumeier.org
description: >- # this means to ignore newlines until "baseurl:"
  Home of Andreas Neumeier.
# baseurl: "/twitter-new" # the subpath of your site, e.g. /blog
markdown: kramdown
url: "https://www.neumeier.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: andreasofthings
github_username:  andreasofthings
