theme: minima
markdown: kramdown
# Site settings
title: Andreas.
email: andreas@neumeier.org
description:  Home of Andreas Neumeier.
url: "https://www.neumeier.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
# date_format: "%b %-d, %Y"
    
# generate social links in footer seems to work like this
twitter_username: andreasofthings
github_username:  andreasofthings
stackoverflow_username: "1569491"	
facebook_username: andreasofthings
flickr_username: andreasofthings
instagram_username: andreasofthings
linkedin_username: andreasofthings
keybase_username: andreasofthings

social:
    name: Andreas Neumeier
    links: 
      - https://twitter.com/andreasofthings
      - https://linkedin.com/in/andreasofthings
      - https://github.com/andreasofthings
 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
titles_from_headings:
    strip_title: true
    collections: true
