baseURL: "https://www.neumeier.org/"
languageCode: "en-us"
title: "neumeier.org"
theme: "zen" # https://github.com/frjo/hugo-theme-zen
# theme: "hugo-PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # necessary for search

markup:
    goldmark:
        renderer:
            unsafe: true

params:
    alpine: true # Add AlpineJS, default false.
    author:
        name: Andreas # Your Name
        url: https://neumeier.org/andreas # https://example.org/somepage
        avatar: # path/to/some-image.jpg
    blogSections: # Sections whose <schema.org> `JSON+LD` in the page `<head>`
        # - blog                  # will be `@type: BlogPosting`.
        - post # Defaults to a list including only 'post' and 'blog'.
    breadcrumbSections: # Sections in which pages will have a `BreadcrumbListing`
        - section2 # in the <schema.org> `JSON+LD` in the page's `<head>`.
        - section3 # This theme requires Hugo `v0.109.0` or higher to
          # generate the `BreadcrumbListing`.
    cookieConsent: true # Show cookie consent form, default false.
    contact: "andreas@neumeier.org"
    dateformat: ""            # Set the date format, default to "2 January, 2006"
    description: ""           # Set site description, used in meta tags and JSON-LD
    favicon: ""               # Relative path to favicon in json feed, no leading slash.
    feedlinks: true           # Show feed links in the footer.
    footer: "1999 - 2005 - [neumeier.org](https://neumeier.org/)."
    icon: ""                  # Relative path to icon in json feed and JSON-LD, no leading slash.
    image: ""                 # Relative path to site image in JSON-LD, no leading slash.
    imageMaxWidth: ""         # Max width for images added via figure shortcode.
    internalPagination: true  # Use Hugos internal pagination template, default false.
    jquery: true              # Add jQuery, default false.
    languageDir: ""           # Set ltr or rtl, defaults to ltr.
    logo: false               # Turn off the logo, defaults to true.
    logoPath:                 # Relative path to site logo, defaults to "images/logo.png", no leading slash.
    logoHeight:               # Set logo height, defaults to none.
    logoWidth:                # Set logo width, defaults to none.
    mainSections:             # The sections you want to have listed on the front page.
      - "section1"            # Default to the section with most content if not set.
      - "section2"            # Set to empty if no section should be listed.
    math: true                # Turn on math typesetting with KaTeX, default false.
    menuInHeader: true        # Move the main menu to the header, default false.
    microUsername: ""         # Your micro.blog username.
    mobileMenu: true          # Turn on a mobile menu on small screens, default false.
    mobileMenuOutline: true   # Mobil menu button as outline, default false.
    piwikSiteId:              # Matomo site id
    piwikTrackerUrl: ""       # Matomo url, schemaless and no slash on end (example.org/matomo).
    plausibleSiteID: ""       # Plausible site id/domain.
    plausibleTrackerURL: ""   # Plausible url, schemaless and no slash on end. Optional, defaults to "plausible.io/…"
    poweredby: true           # Show powered by hugo in footer
    privacyPolicyUrl: ""      # If set will add link to cookie consent form.
    relatedposts: true        # Show related posts under a "See also" section, default false.
    sassTranspiler: "dartsass"# The Sass transpiler to use, default "libsass".
    searchLimit: 20           # Max number of search hits, default 20.
    sidebar: true             # Show a sidebar to the right, default false.
    siteName: false           # Hide the site name (visually-hidden), default true.
    submitted: true           # Show author and date information for a post.
    themeColor:               # Hex color value, used in meta tags, default "#ffffff".
    umbrella: true            # Add Umbrella JS, default false.

    podcast:
      title:                  # * Feed title, defaults to site title (iTunes).
      description:            # * Feed description/summary, defaults to  site description (iTunes).
      image:                  # * Feed image, place inside assets directory (iTunes).
      category:
        name:                 # * Feed category (iTunes).
        subcategories: []     # Feed sub category (iTunes).
      explicit: false/true    # Feed explicit setting, default to false (iTunes).
      author:                 # Feed author (iTunes).
      owner:
        name:                 # Feed owner name (iTunes).
        email:                # Feed owner e-mail (iTunes).
      lang:                   # Feed language, defaults to site language (iTunes).
      block: no/yes           # Block the feed from iTunes, default to no (iTunes).
      complete: no/yes        # Set the feed as complete, defaults to no (iTunes).
      type: episodic/serial   # Podcast type, defaults to episodic (iTunes).
      newfeed:                # Are you moving? Set the new feed url here (iTunes).
      cdn:                    # CDN url, no slash on end (https://cdn.example.org).
      local: false            # Are the audio files local (true) or remote (false), default to true.
      preload: none/metadata/auto # Set on the HTML5 audio tag, defaults to "metadata".
# from hugo papermod
#  env: production # to enable google analytics, opengraph, twitter-cards and schema.
#  title: home
#  description: "homepage"
#  keywords: [Blog, Portfolio, Andreas, Site, WebSite, Enterprise, Software, Product, Privacy]
#  author:
#    name: Andreas Neumeier  # author: ["Me", "You"] # multiple authors
#  contact: andreas@neumeier.org
# images: ["/Transparent Logo.png"]
#  DateFormat: "January 2, 2026"
#  defaultTheme: auto # dark, light
#  disableThemeToggle: false

#  ShowReadingTime: true
#  ShowShareButtons: true
#  ShareButtons: ["linkedin", "mastodon", "reddit"]
#  ShowPostNavLinks: true
#  ShowBreadCrumbs: true
#  ShowCodeCopyButtons: true
#  ShowWordCount: true
#  ShowRssButtonInSectionTermList: true
#  UseHugoToc: true
#  disableSpecial1stPost: false
#  disableScrollToTop: false
#  comments: false
#  hidemeta: false
#  hideSummary: false
#  showtoc: false
#  tocopen: false

#  cover:
#    hidden: true # hide everywhere but not in structured data
#    hiddenInList: true # hide on list pages and home
#    hiddenInSingle: true # hide on single page

#  profileMode:
#    enabled: true
#    title: "product / privacy." # optional default will be site title
#    subtitle: "
#    ####
#
#    ##### Andreas
#    "
#    # imageUrl: "/Transparent Logo.png" # optional
#    # imageTitle: "Grumpy me on the internet." # optional
#    # imageWidth: 120 # custom size
#    # 	imageHeight: 120 # custom size
#    buttons:
#      - name: "ideate."
#        url: "https://calendar.app.google/HtmDbH3wV4EcPjUX7"
#      - name: "product."
#        url: "https://pramari.de/"

#  socialIcons: # optional
#    - name: mastodon
#      url: "https://23.social/@andreasofthings"
#    - name: linkedin
#      url: "https://www.linkedin.com/in/andreasofthings/"
#    - name: github
#      url: "https://github.com/andreasofthings"
#    - name: youtube
#      url: "https://youtube.com/@labstalkdev"
#    - name: matrix
#      url: "https://matrix.to/#/@andreas:pramari.de"
#    - name: rss
#      url: "https://nomorecubes.net/feed"
#    - name: signal
#      url: "https://signal.me/#eu/l53hzJl6d4OYArhgIEW3pgu3fK89dDNVFrMuyj8kAXKMGq82_yNCl44NuVOitYU8"

#  editPost:
#    URL: "https://github.com/andreasofthings/neumeier.org/tree/main/content"
#    Text: "Suggest Changes" # edit text
#    appendFilePath: true # to append file path to Edit link

#menu:
#  main:
#    - identifier: impressum
#      name: impressum
#      url: /posts/imprint/
#      weight: 30
#    - identifier: search
#      name: search
#      url: /search/
#      weight: 20
#    - identifier: links
#      name: links
#      url: /links/
#      weight: 10
