baseURL = "https://www.neumeier.org/"
languageCode = "en-us"
title = "neumeier.org"
theme = "hallo"

[Author]
    name = "Andreas"

[params]
  [[params.links]]
    icon = "github"
    title = "andreasofthings Github"
    url = "https://github.com/andreasofthings"
  [[params.links]]
    icon = "twitter"
    title = "andreasofthings twitter"
    url = "https://twitter.com/andreasofthings"
  [[params.links]]
    icon = "linkedin"
    title = "andreasofthings linkedin"
    url = "https://www.linkedin.com/in/andreasofthings"
  [[params.links]]
    icon = "instagram"
    title = "andreasofthings instagram"
    url = "https://instagram.com/andreasofthings"
  [[params.links]]
    iconset = "fas"
    icon = "rss"
    title = "andreasofthings rss"
    url = "https://nomorecubes.net/feed/"
  [[params.links]]
    iconset = "fas"
    icon = "envelope"
    title = "E-mail"
    url = "mailto:andreas@neumeier.org" 
  [[params.links]]
     iconset = "fas"
        icon = "info-circle"
        title = "Additional information"
        url = "#info"

[params.colors]
    background = "#818181"
    foreground = "#edf7ff"
    hover = "#ffba82"
    
  # favicon = ""
  # facebook = ""
  # youtube = ""
  # gitlab = ""
  # mastodon = ""
  # slack = ""
  # stackoverflow = ""

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  # recent_posts_number = 2
