baseURL = "https://www.neumeier.org/"
languageCode = "en-us"
title = "neumeier.org"
theme = "hallo"
# theme        = "hello-friend-ng"
# theme        = ["github.com//rhazdon/hugo-theme-hello-friend-ng"]
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[Author]
    name = "Andreas"

[params]
  [[params.links]]
    icon = "github"
    title = "Github"
    url = "https://github.com/andreasofthings"
  [[params.links]]
    icon = "twitter"
    title = "twitter"
    url = "https://twitter.com/andreasofthings"
  [[params.links]]
    icon = "linkedin"
    title = "linkedin"
    url = "https://www.linkedin.com/in/andreasofthings"
  favicon = ""
  facebook = ""
  instagram = "https://instagram.com/andreasofthings"
  youtube = ""
  # github = "https://github.com/andreasofthings"
  gitlab = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  # recent_posts_number = 2
