baseURL: "https://www.neumeier.org/"
languageCode: "en-us"
title: "neumeier.org"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: home
  description: "homepage"
  keywords: [Blog, Portfolio, Andreas, Site, WebSite, Enterprise, Software]
  author: Andreas Neumeier  # author: ["Me", "You"] # multiple authors
  images: ["/Transparent Logo.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter", "reddit"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  profileMode:
    enabled: true
    title: "product guy." # optional default will be site title
    subtitle: "
    ## and design thinking coach.

    "
    imageUrl: "/Transparent Logo.png" # optional
    imageTitle: "Grumpy me on the internet." # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: "ideate."
        url: "https://calendar.app.google/HtmDbH3wV4EcPjUX7"
      - name: "product."
        url: "https://pramari.de/"
      - name: "subscribe."
        url: "https://buttondown.email/showcaseproduct?tag=website"

  socialIcons: # optional
    - name: mastodon
      url: "https://23.social/@andreasofthings"
    - name: linkedin
      url: "https://www.linkedin.com/in/andreasofthings/"
    - name: github
      url: "https://github.com/andreasofthings"
    - name: youtube
      url: "https://youtube.com/@labstalkdev"
    - name: matrix
      url: "https://matrix.to/#/@andreas:pramari.de"
    - name: rss
      url: "https://nomorecubes.net/feed"
    - name: signal
      url: "https://signal.me/#eu/l53hzJl6d4OYArhgIEW3pgu3fK89dDNVFrMuyj8kAXKMGq82_yNCl44NuVOitYU8"
 
  editPost:
    URL: "https://github.com/andreasofthings/neumeier.org/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

menu:
  main:
    - identifier: impressum
      name: impressum
      url: /posts/imprint/
      weight: 30
