baseURL = "https://www.neumeier.org/"
languageCode = "en-us"
title = "neumeier.org"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]


[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/andreasofthings"
  instagram = "https://instagram.com/andreasofthings"
  youtube = ""
  github = "https://github.com/andreasofthings"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/andreasofthings"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  # recent_posts_number = 2
